### ISSUE TITLE
Analizar y comprender el problema

### ISSUE THREAD

**Issue by juanmendiola** [juanmendiola/EafitCommute#1]
1. Video sobre la problematica (Nicolas Rico)
2. Descripcion de la problematica ( Jairo Diaz)
3. Esquema de la problematica seleccionada ( Juan Mendiola)
4. Idea solucion ( Nicolas Rico)
5. Funcionalidades / caracteristicas de la solución ( Deivid Echeverry)
6. Plan de trabajo ( Juan Mendiola)

**Comment by Nicolas147-f4** [comment]
1. Video sobre la problematica (Nicolas Rico)
